#!/bin/bash
foSite="repositories/fo-site"
userDir=/home/$1

echo "Removing $userDir/$foSite/app/cache/prod"
sudo rm -rf ${userDir}/${foSite}/app/cache/prod
echo "Removing $userDir/$foSite/app/cache/dev"
sudo rm -rf ${userDir}/${foSite}/app/cache/dev
echo "Removing $userDir/$foSite/app/cache/console"
sudo rm -rf ${userDir}/${foSite}/app/cache/console
echo "Removing $userDir/$foSite/app/config/configuration.yml"
sudo rm -rf ${userDir}/${foSite}/app/config/configuration.yml