#!/bin/bash

source setup.sh

repo=$1
repoPath="repositories/$repo"
testUnitPath=/${repoPath}/tests/unit
bootstrap=/${repoPath}/vendor/autoload.php
configuration=${testUnitPath}/phpunit.xml

${SUDO_COMMAND} docker-compose kill
${SUDO_COMMAND} docker-compose up --build -d
${SUDO_COMMAND} docker exec -ti php56 /bin/bash -c "(cd /$repoPath && composer install);/$repoPath/vendor/bin/phpunit $testUnitPath --bootstrap $bootstrap --configuration $configuration"
