#!/bin/bash
source setup.sh

foSite="repositories/fo-site"
testUnitPath=/${foSite}/tests/unit
bootstrap=${testUnitPath}/bootstrap.php
configuration=${testUnitPath}/phpunit.xml

${SUDO_COMMAND} ./clearCache
${SUDO_COMMAND} docker-compose kill
${SUDO_COMMAND} docker-compose up --build -d
${SUDO_COMMAND} docker exec -ti php56 /bin/bash -c "/bin/phpunit $testUnitPath --bootstrap $bootstrap --configuration $configuration"
${SUDO_COMMAND} ./clearCache
