#!/bin/bash

source setup.sh

${SUDO_COMMAND} docker run -ti -v ${REPOSITORY_DIR}:/repositories npm /bin/bash -c "(cd /repositories/fo-site-ui; npm install; node ./npm_scripts/css-build.js --sites currys --env dev)"
