#!/bin/bash

source setup.sh

foSite="repositories/fo-site"

${SUDO_COMMAND} ./clearCache
${SUDO_COMMAND} docker-compose kill
${SUDO_COMMAND} docker-compose up --build -d
${SUDO_COMMAND} docker exec -ti php56 /bin/bash -c "(cd /${foSite}; composer install)"