#!/bin/bash

source setup.sh

foSite="fo-site"

echo "Removing $REPOSITORY_DIR/$foSite/app/cache/prod"
${SUDO_COMMAND} rm -rf ${REPOSITORY_DIR}/${foSite}/app/cache/prod
echo "Removing $REPOSITORY_DIR/$foSite/app/cache/dev"
${SUDO_COMMAND} rm -rf ${REPOSITORY_DIR}/${foSite}/app/cache/dev
echo "Removing $REPOSITORY_DIR/$foSite/app/cache/console"
${SUDO_COMMAND} rm -rf ${REPOSITORY_DIR}/${foSite}/app/cache/console
echo "Removing $REPOSITORY_DIR/$foSite/app/config/configuration.yml"
${SUDO_COMMAND} rm -rf ${REPOSITORY_DIR}/${foSite}/app/config/configuration.yml