#!/bin/bash

source setup.sh

foSite="fo-site"
foSiteApp="$REPOSITORY_DIR/$foSite/app"
foSiteCache="$foSiteApp/cache"

echo "Removing $foSiteCache/prod"
${SUDO_COMMAND} rm -rf ${foSiteCache}/prod

echo "Removing $foSiteCache/dev"
${SUDO_COMMAND} rm -rf ${foSiteCache}/dev

echo "Removing $foSiteCache/console"
${SUDO_COMMAND} rm -rf ${foSiteCache}/console

echo "Removing $foSiteApp/config/configuration.yml"
${SUDO_COMMAND} rm -rf ${foSiteApp}/config/configuration.yml