#!/bin/bash

source setup.sh

status=$1
foSite=$REPOSITORY_DIR/fo-site
webDir=${foSite}/web
wwwDir=${foSite}/www
htaccess=${wwwDir}/.htaccess
htaccessProfiler=${wwwDir}/.htaccess.PD-1010
htaccessOriginal=${wwwDir}/.htaccess.original
appDevProfiler="resources/fo-site/app_dev.php"
appDev=${webDir}/app_dev.php
appDevOriginal=${appDev}.original
webDevProfiler="resources/fo-site/web.php"
webDev=${wwwDir}/web.php
webDevOriginal=${webDev}.original


# ___/\_Backup_/\___
if [ ! -f "$appDevOriginal" ]; then
${SUDO_COMMAND} cp ${appDev} ${appDevOriginal}
fi

if [ ! -f "$htaccessOriginal" ]; then
${SUDO_COMMAND} cp ${htaccess} ${htaccessOriginal}
fi

if [ ! -f "$webDevOriginal" ]; then
${SUDO_COMMAND} cp ${webDev} ${webDevOriginal}
fi

echo "Switching"
# ___/\Switch/\___
if [ "$status" = "enable" ]; then
	${SUDO_COMMAND} cp ${appDevProfiler} ${appDev}
	${SUDO_COMMAND} cp ${htaccessProfiler} ${htaccess}
	${SUDO_COMMAND} cp ${webDevProfiler} ${webDev}
elif [ "$status" = "disable" ]; then
	${SUDO_COMMAND} cp ${appDevOriginal} ${appDev}
	${SUDO_COMMAND} cp ${htaccessOriginal} ${htaccess}
	${SUDO_COMMAND} cp ${webDevOriginal} ${webDev}
elif [ "$status" = "clear" ]; then
	${SUDO_COMMAND} rm ${webDevOriginal}
	${SUDO_COMMAND} rm ${htaccessOriginal}
	${SUDO_COMMAND} rm ${appDevOriginal}
else
	echo "Bad argument, use enable/disable or clear"
fi

echo "Clearing cache"
clearCache

echo "as next step clear cache on your dev"
echo "Please use this inside /web_dir/fo-currys"
echo "- rm -rf app/cache/dev"
echo "- rm -rf app/config/configuration.yml"
